#=========================================================================
# GDS Pre-Merge
#=========================================================================
# Author : Nikhil Poole
# Date   : July 9, 2021
#

name: premerge

#-------------------------------------------------------------------------
# Outputs
#-------------------------------------------------------------------------

outputs:
  - design.gds
  - user_analog_project_wrapper_digital_abstracted.gds
#  - sky130_sram_4kbyte_1rw1r_32x1024_8.gds
  - sky130_sram_2kbyte_1rw1r_32x512_8.gds

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - cp design.gds outputs/
  - cp user_analog_project_wrapper_digital_abstracted.gds outputs/
#  - cp ~/PDKS/sky130A/libs.ref/sky130_sram_macros/gds/sky130_sram_4kbyte_1rw1r_32x1024_8.gds outputs/
  - cp ~/PDKS/sky130A/libs.ref/sky130_sram_macros/gds/sky130_sram_2kbyte_1rw1r_32x512_8.gds outputs/