#=========================================================================
# Extract spice from GDS using Magic
#=========================================================================
# Author : Nikhil Poole
# Date   : June 21, 2021
#

name: open-magic-gds2spice-nobbox

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------
inputs:
  - adk
  - design_merged.gds
#  - sky130_sram_4kbyte_1rw1r_32x1024_8.lef
  - sky130_sram_2kbyte_1rw1r_32x512_8.lef

outputs:
  - design_extracted.spice

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  design_name: undefined

commands:
  - cp /home/users/nhpoole/PDKS/sky130A/libs.tech/magic/sky130A.magicrc .magicrc
  - magic -noconsole -dnull extract.tcl | tee gds2spice.log
  - mv {design_name}.spice outputs/design_extracted.spice
