#=========================================================================
# DRC using magic
#=========================================================================
# Author : Nikhil Poole
# Date   : June 12, 2021
#

name: open-magic-drc

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------
inputs:
  - adk
  - design_merged.gds

outputs:
  - drc_results.log

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  design_name: undefined

commands:
  - cp /home/users/nhpoole/PDKS/sky130A/libs.tech/magic/sky130A.magicrc .magicrc
  - cp inputs/adk/sky130A.tech sky130A.tech
  - cp inputs/adk/sky130A.tcl sky130A.tcl
  - cp inputs/*.lef .
  - magic -noconsole -dnull run_drc.tcl | tee outputs/drc_results.log
  - grep "error" outputs/drc_results.log
