#=========================================================================
# Extract spice from GDS using magic
#=========================================================================
# Author : Nikhil Poole
# Date   : June 11, 2021
#

name: open-magic-gds2spice

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------
inputs:
  - adk
  - design_merged.gds

outputs:
  - design_extracted.spice

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  design_name: undefined

commands:
  - cp /home/users/nhpoole/PDKS/sky130A/libs.tech/magic/sky130A.magicrc .magicrc
  - magic -noconsole -dnull extract.tcl | tee gds2spice.log
  - mv {design_name}.spice outputs/design_extracted.spice
