#=========================================================================
# Constraints
#=========================================================================
# Author : Nikhil Poole
# Date   : Jun 4, 2021
#

name: constraints

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - constraints.tcl

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  clock_period: 20.0
  design_name: undefined

commands: 
  - cat constraints.tcl > outputs/constraints.tcl
