#=========================================================================
# Calibre LVS Setup
#=========================================================================
# Author : Nikhil Poole
# Date   : June 21, 2021
#

name: lvs_setup

#-------------------------------------------------------------------------
# Outputs
#-------------------------------------------------------------------------

outputs:
  - deconv.lvs.v
  - deconv.nofillerlvs.v
  - deconv.flatbuslvs.v
  - deconv.nofillerflatbuslvs.v
  - adc_controller.lvs.v
  - adc_controller.nofillerlvs.v
  - adc_controller.flatbuslvs.v
  - adc_controller.nofillerflatbuslvs.v
#  - sky130_sram_4kbyte_1rw1r_32x1024_8.lef
#  - sky130_sram_4kbyte_1rw1r_32x1024_8.sp
  - sky130_sram_2kbyte_1rw1r_32x512_8.lef
  - sky130_sram_2kbyte_1rw1r_32x512_8.sp
  - design_extracted.spice
  - user_analog_project_wrapper.spice

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - cp deconv.lvs.v deconv.nofillerlvs.v deconv.flatbuslvs.v deconv.nofillerflatbuslvs.v outputs/
  - cp adc_controller.lvs.v adc_controller.nofillerlvs.v adc_controller.flatbuslvs.v adc_controller.nofillerflatbuslvs.v outputs/
#  - cp ~/PDKS/sky130A/libs.ref/sky130_sram_macros/lef/sky130_sram_4kbyte_1rw1r_32x1024_8.lef outputs/
#  - cp ~/PDKS/sky130A/libs.ref/sky130_sram_macros/spice/sky130_sram_4kbyte_1rw1r_32x1024_8.sp outputs/
  - cp ~/PDKS/sky130A/libs.ref/sky130_sram_macros/lef/sky130_sram_2kbyte_1rw1r_32x512_8.lef outputs/
  - cp ~/PDKS/sky130A/libs.ref/sky130_sram_macros/spice/sky130_sram_2kbyte_1rw1r_32x512_8.sp outputs/
  - cp design_extracted.spice outputs/
  - cp user_analog_project_wrapper.spice outputs/
