#=========================================================================
# Comparison of netlists using Calibre
#=========================================================================
# Author : Nikhil Poole
# Date   : June 21, 2021
#

name: mentor-calibre-comparison-nobbox

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------
inputs:
  - adk
  - design_extracted.spice
  - design.nofillerflatbuslvs.v
#  - sky130_sram_4kbyte_1rw1r_32x1024_8.sp
  - sky130_sram_2kbyte_1rw1r_32x512_8.sp

outputs:
  - lvs.report

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  design_name: undefined

commands: 
  - sed -i 's/VNB sky130_fd_pr__res_generic_po/sky130_fd_pr__res_generic_po/g' inputs/adk/stdcells.spi
  - sh run_lvs.sh

debug:
  - calibre -rve -lvs svdb

