#=========================================================================
# Run antenna check
#=========================================================================
# Author : Nikhil Poole
# Date   : June 12, 2021
#

name: open-magic-antenna

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------
inputs:
  - adk
  - design.def.gz

outputs:
  - antenna_check.log

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  design_name: undefined

commands:
  - cp /home/users/nhpoole/PDKS/sky130A/libs.tech/magic/sky130A.magicrc .magicrc
  - cp inputs/adk/rtk-tech.lef rtk-tech-nolicon.lef
  - sed -i '/LAYER licon/,/END licon/d' rtk-tech-nolicon.lef
  - cp -L inputs/design.def.gz design.def.gz 
  - gunzip design.def.gz 
  - magic -noconsole -dnull run_antenna.tcl | tee outputs/antenna_check.log
