#=========================================================================
# OpenRAM SRAM Compiler 
#=========================================================================
# Author : Nikhil Poole
# Date   : June 12, 2021
#

name: sram

#-------------------------------------------------------------------------
# Outputs
#-------------------------------------------------------------------------

outputs:
#  - sky130_sram_8kbyte_1rw1r_32x2048_8.sp
#  - sky130_sram_8kbyte_1rw1r_32x2048_8.v
#  - sky130_sram_8kbyte_1rw1r_32x2048_8.lef
#  - sky130_sram_8kbyte_1rw1r_32x2048_8_TT_1p8V_25C.lib
#  - sky130_sram_8kbyte_1rw1r_32x2048_8.gds
#  - sky130_sram_8kbyte_1rw1r_32x2048_8_TT_1p8V_25C.db
  - sky130_sram_4kbyte_1rw1r_32x1024_8.sp
  - sky130_sram_4kbyte_1rw1r_32x1024_8.v
  - sky130_sram_4kbyte_1rw1r_32x1024_8.lef
  - sky130_sram_4kbyte_1rw1r_32x1024_8_TT_1p8V_25C.lib
  - sky130_sram_4kbyte_1rw1r_32x1024_8.gds
  - sky130_sram_4kbyte_1rw1r_32x1024_8_TT_1p8V_25C.db

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
#  - cp ~/PDKS/sky130A/libs.ref/sky130_sram_macros/spice/sky130_sram_8kbyte_1rw1r_32x2048_8.sp outputs/
#  - cp ~/PDKS/sky130A/libs.ref/sky130_sram_macros/verilog/sky130_sram_8kbyte_1rw1r_32x2048_8.v outputs/
#  - cp ~/PDKS/sky130A/libs.ref/sky130_sram_macros/lef/sky130_sram_8kbyte_1rw1r_32x2048_8.lef outputs/
#  - cp ~/PDKS/sky130A/libs.ref/sky130_sram_macros/lib/sky130_sram_8kbyte_1rw1r_32x2048_8_TT_1p8V_25C.lib outputs/
#  - cp ~/PDKS/sky130A/libs.ref/sky130_sram_macros/gds/sky130_sram_8kbyte_1rw1r_32x2048_8.gds outputs/
#  - cp ~/PDKS/sky130A/libs.ref/sky130_sram_macros/lib/sky130_sram_8kbyte_1rw1r_32x2048_8_TT_1p8V_25C.db outputs/
  - cp ~/PDKS/sky130A/libs.ref/sky130_sram_macros/spice/sky130_sram_4kbyte_1rw1r_32x1024_8.sp outputs/
  - cp ~/PDKS/sky130A/libs.ref/sky130_sram_macros/verilog/sky130_sram_4kbyte_1rw1r_32x1024_8.v outputs/
  - cp ~/PDKS/sky130A/libs.ref/sky130_sram_macros/lef/sky130_sram_4kbyte_1rw1r_32x1024_8.lef outputs/
  - cp ~/PDKS/sky130A/libs.ref/sky130_sram_macros/lib/sky130_sram_4kbyte_1rw1r_32x1024_8_TT_1p8V_25C.lib outputs/
  - cp ~/PDKS/sky130A/libs.ref/sky130_sram_macros/gds/sky130_sram_4kbyte_1rw1r_32x1024_8.gds outputs/
  - cp ~/PDKS/sky130A/libs.ref/sky130_sram_macros/lib/sky130_sram_4kbyte_1rw1r_32x1024_8_TT_1p8V_25C.db outputs/

#  - sed -i '/SHAPE ABUTMENT/d' outputs/sky130_sram_8kbyte_1rw1r_32x2048_8.lef
  - sed -i '/SHAPE ABUTMENT/d' outputs/sky130_sram_4kbyte_1rw1r_32x1024_8.lef
    